language: generic

branches:
  except:
    - gh-pages

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main"
              key_url: "https://packages.microsoft.com/keys/microsoft.asc"
          packages:
            - powershell
  fast_finish: true

install:
  - pwsh -c "Install-Module -Name Pester -Force | Out-Null"
  - pwsh -c "Import-Module ${env:TRAVIS_BUILD_DIR}/build/travis.psm1"

script:
  - pwsh -c "Invoke-TravisTest"