site_name: Pode
nav:
  - Home: index.md
  - Getting Started:
    - Installation: Getting-Started/Installation.md
    - CLI: Getting-Started/CLI.md
    - Docker: Getting-Started/Docker.md
    - Frontend: Getting-Started/Frontend.md
    - Cron Expressions: Getting-Started/CronExpressions.md
  - Tutorials:
    - Routes: Tutorials/Routes.md
  - Functions:
    - Attach: Functions/Attach.md
    - Csv: Functions/Csv.md
    - Dispose: Functions/Dispose.md
    - Endware: Functions/Endware.md
    - Engine: Functions/Engine.md
    - Html: Functions/Html.md
    - Json: Functions/Json.md
    - Listen: Functions/Listen.md
    - Lock: Functions/Lock.md
    - Middleware: Functions/Middleware.md
    - Redirect: Functions/Redirect.md
    - Route: Functions/Route.md
    - Schedule: Functions/Schedule.md
    - Server: Functions/Server.md
    - Session: Functions/Session.md
    - Status: Functions/Status.md
    - Stream: Functions/Stream.md
    - Stopwatch: Functions/Stopwatch.md
    - Timer: Functions/Timer.md
    - View: Functions/View.md
    - Xml: Functions/Xml.md
theme:
  name: material
  logo: images/icon.png
  favicon: images/favicon.ico
  feature:
    tabs: true
  palette:
    primary: cyan
    accent: cyan
markdown_extensions:
  - codehilite
  - admonition
  - meta
repo_name: badgerati/pode
repo_url: https://github.com/Badgerati/Pode
extra:
  social:
    - type: github
      link: https://github.com/badgerati
    - type: twitter
      link: https://twitter.com/badgerati