name: Pode CI

on:
  push:
    branches:
    - '*'
    - '!gh-pages'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-16.04, windows-latest, windows-2016, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install Invoke-Build
      shell: pwsh
      run: Install-Module -Name InvokeBuild -RequiredVersion '5.5.1' -Force

    - name: Run Pester Tests
      shell: pwsh
      env:
        PODE_COVERALLS_TOKEN: ${{ secrets.PODE_COVERALLS_TOKEN }}
        PODE_RUN_CODE_COVERAGE: ${{ matrix.os == 'windows-latest' }}
      run: Invoke-Build Test